version: '3.8'

services:
  server_api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port ${APPLICATION_PORT} --reload
    # command: python app/main.py
    volumes:
      - .:/app
    restart: always
    ports:
      - "${APPLICATION_PORT}:${APPLICATION_PORT}"
    depends_on:
      - v2ray
    environment:
      - V2RAY_API_HOST=${V2RAY_API_HOST}
      - V2RAY_API_PORT=${V2RAY_API_PORT}
      - CONFIG_PATH=${CONFIG_PATH}

  v2ray:
    image: v2fly/v2fly-core
    restart: always
    command: ["run", "-config=/etc/v2ray/config.json"]
    volumes:
      - ${CONFIG_PATH}:/etc/v2ray/config.json
    ports:
      - "${V2RAY_API_PORT}:${V2RAY_API_PORT}"
      - "${V2RAY_PORT}:${V2RAY_PORT}"


      
